package drools.common
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import org.apache.commons.lang.StringUtils;


declare Room
    creater:String
	name: String
	id:String
	setting:Map
	version:String
	status:String
	
end

declare Right
       id:String
       right:Set
       isNotify:boolean
end

declare Player
	id: String
	name: String
	status: String		
end

declare Snapshot
    id:Long
end