package drools.common
import drools.common.*;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.Collections;



import org.apache.commons.lang.StringUtils;




function void setRemainTime(String status,Game game,Room room) {

     if("day"==status){
       status="dayTime";
     };
     
     if("night"==status){
       status="nightTime";
     };
     
     if("lastword"==status){
       status="lastwordTime";
     };
     
    
     Long setting=Long.valueOf(getRoomSetting(room,status,"-1"));
      Long lastTime=game.getLastTime();
      Long time=lastTime+setting-System.currentTimeMillis();
      if(time < 0){
             
      }else{
          game.setRemainTime(time);
      }
     
       
}





 














