package drools.common

import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import org.apache.commons.lang.StringUtils;
import com.sun.tools.javac.util.Pair;



declare Game
	status: String	
	lastTime:Long
	remainTime:Long
	startAt:Long
	recordName:String	
	playerCount:Integer	
end

declare BombPic
        system:String
        user:String
end

declare Pane 
    
     id:String
     coordinate:Pair
     value:String#如果.是雷就是m. 标记为雷是t, 其它的就是周围雷的数目.	
     tag:String#用户的标记  
     
end


declare Click      
     uid:String     
     value:String
     pid:String
end
#这个Tag不只是用户标记.用户点开的内容都有的
declare Tag 
     uid:String  
     value:String
     pid:String
     
end

declare Count
        bomb:Integer
        all:Integer
        init:Integer
end

