package drools.common

import drools.common.*
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.Collections;



import org.apache.commons.lang.StringUtils;
//需要重置的资源最好和不需要重置的资源分开,这样清除的时候容易很多,可以考虑把所有的资源都加上GameID.统一清空




function void setRemainTime(String status,Game game,Room room) {

    
     Long setting=Long.valueOf(getRoomSetting(room,status+"Time","-1"));
      Long lastTime=game.getLastTime();
      game.setRemainTime(lastTime-setting);
       
}





 














