package drools.common

import drools.common.*
import com.gemantic.killer.common.model.Message
import com.gemantic.killer.common.model.Operater;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import com.gemantic.common.util.json.GsonUtil;
import java.util.HashMap;
import java.util.Map;
import org.apache.commons.lang.math.RandomUtils;
import org.apache.commons.lang.StringUtils;
import com.gemantic.killer.util.*;
import com.gemantic.common.drools.util.LogUtil;










#========================query group start =========================














rule 'bomb assign'
ruleflow-group "game init"
when
	
    $message:Message(predict=="start",$time:time)
    
    
    $allReadys:ArrayList()
	      from accumulate(
	      $person:Player(status=="ready")	     
	      init(List ls=new ArrayList();),
	      action(ls.add($person);),
	      result(ls)
	      );
    
    $room:Room(status=="unrun")    
     $operater:Operater()
then      
	LogUtil.log("bomb assign  =================");
	LogUtil.log($allReadys);
	 int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));#1*60*1000  
	 int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));#1*60*1000  
	 int  bombCount=Integer.valueOf(getRoomSetting($room,"雷数","10"));#1*60*1000  

     String systemBombPic=BombUtil.assign(rowCount,columnCount,bombCount);
     LogUtil.log(" systemBombPic ================= "+systemBombPic);
     BombPic bombPic=new BombPic(systemBombPic,"");
     insert(bombPic);
     
     //init user bomb count
     
     for(Object o: $allReadys){
     
        Player p=(Player)o;
          String uid=p.getId();
			
				  
				  UserCount uc=new UserCount(uid,0);
				  insert(uc);	  
				  Message assignMessage=new Message(uid,"count","0");
				  insert(assignMessage);	  
     
     }
     
	
	String	rname=String.valueOf(RandomUtils.nextLong());	
	
	
	Game game=new Game("run",System.currentTimeMillis(),0L,$time,rname, $allReadys.size());
	insert(game);
	
	LogUtil.log(" game status  ================="+game);
	
	Count count=new Count(0,bombCount,rowCount*columnCount);
	insert(count);
	
	$room.setStatus("run");	
	update($room);
	$operater.setGameStart(true);
	Message initMessage=new Message("","init",systemBombPic);
	insert(initMessage); 
	
	LogUtil.log("role assign process over  =================");
end



rule 'clear tag'
ruleflow-group "game init"
when
	
    $message:Message(predict=="start",$time:time)   
    $room:Room(status=="unrun")    
    $operater:Operater()
    $tag:Tag()   
then      

	LogUtil.log("clear tag start  =================");	
    retract($tag);

	LogUtil.log("clear tag over  =================");
end





rule 'start game right'
ruleflow-group "game right"
no-loop true
when

    $message:Message(predict=="start");
    $person:Player($id:id)
    $right:Right(id==$id)
    Game()
    

	
then      
    LogUtil.log("start game right   start ============= "+$message);
    
	$right.setRight(convertString2Set("say"));
	LogUtil.log(" =============");
	$right.setIsNotify(false);
    LogUtil.log(" ============="+$right);
    update($right);
    LogUtil.log(" =============");    
    LogUtil.log("start game right  over =============");
end



rule 'game over right'
ruleflow-group "game right"
no-loop true
when
	
	$message:Message(predict=="over")
	not Game()
	$room:Room($creater:creater)
    $person:Player($id:id)
    $right:Right(id==$id)

then      
    LogUtil.log("game over  right start   =============");
    $right.setRight(convertString2Set("say,ready"));
    $right.setIsNotify(false); 		
    update($right);
   
    LogUtil.log("game over  right  over =============");
end









#========================action group start =========================

rule 'click pane'
ruleflow-group "user action"
no-loop true
when
    $message:Message($subject:subject,$object:object,predict=="click")   
    $bombPic:BombPic($system:system,$user:user)    
    $room:Room() 
then
    LogUtil.log("click pane start  ================="); 
    
     Pair p=BombUtil.convertString2Pair($object);   
     
     int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));#1*60*1000  
     LogUtil.log("=========");
	 int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));#1*60*1000  	 
	 
	  LogUtil.log("=========");
    String userTag=BombUtil.clickOpen(p,$system,rowCount,columnCount);     
   
    //  LogUtil.log("=========");
    Click click=new Click($subject,userTag,$object);
      LogUtil.log("=========");
    insert(click);     
   // Tag tag=new Tag($subject,pane,BombUtil.convertPair2String(pane.getCoordinate()));
    //  LogUtil.log("=========");
  //  insert(tag);   
    
    retract($message);
    
    LogUtil.log("click pane over  ================="); 
end


#tag Pane 
rule 'tag pane'
ruleflow-group "user action"
no-loop true
when
     $room:Room()
    $message:Message($subject:subject,$object:object,predict=="tag")
    $bombPic:BombPic($system:system,$user:user)    
    not Tag(pid==$object)
    $count:Count($bomb:bomb)
    $userCount:UserCount($uc:count,uid==$subject)
then
    LogUtil.log("tag pane start  ================="); 
     Pair p=BombUtil.convertString2Pair($object);
     insert(p);
      int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));#1*60*1000  
      LogUtil.log("=========");
	 int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));#1*60*1000  
    String userTag=BombUtil.clickOpen(p,$system,rowCount,columnCount);    
        
    Message tagMessage=new Message($object,"mine","#");
    insert(tagMessage);     
    $bomb=$bomb+1;    
    $count.setBomb($bomb);
    update($count);
    LogUtil.log("count is   ================="+$count);
    
    $uc=$uc+1; 
      Message ucMessage=new Message($subject,"count",String.valueOf($uc));
    insert(ucMessage);     
       
    $userCount.setCount($uc);
    update($userCount);
    LogUtil.log("user count is   ================="+$uc);
    
    
    Tag tag=new Tag($subject,"#",$object);
    insert(tag);
    retract($message);
    
    LogUtil.log("tag pane over  ================="); 
end

#tag Pane
rule 'clear tag pane'
ruleflow-group "clear tag action"
no-loop true
when
     $room:Room()
    $message:Message($subject:subject,predict=="tag",$object:object)  
    $count:Count($bomb:bomb)
    $tag:Tag(pid==$object,value=="#")
     $userCount:UserCount($uc:count,uid==$subject)
       
then
    LogUtil.log("clear tag pane start  ================="); 
   
    $bomb=$bomb-1;
    $count.setBomb($bomb);
    update($count);
    
      $uc=$uc-1; 
      Message ucMessage=new Message($subject,"count",String.valueOf($uc));
    insert(ucMessage);     
       
    $userCount.setCount($uc);
    update($userCount);
    LogUtil.log("user count is   ================="+$uc);
    
    
    
    retract($tag);
    retract($message);
    Message m=new Message($object,"mine","clear");
    insert(m);
    
    LogUtil.log("clear tag pane over  ================="); 
end







rule 'double click pane'
ruleflow-group "user action"

when
    $message:Message($subject:subject,predict=="double click",$object:object)
    $bombPic:BombPic($system:system,$user:user) 
    $room:Room()
   
then
    LogUtil.log("double click pane start  ================= "+$object+" system "+ $system);
 
        Pair pair=BombUtil.convertString2Pair($object);
     int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));#1*60*1000  
      LogUtil.log("=========");
	 int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));#1*60*1000  
	  LogUtil.log("=========");
    List<Pair> roundPanes=BombUtil.getRoundPanes(pair,rowCount,columnCount);
     LogUtil.log("=========");
      LogUtil.log("roundPanes  ================= "+roundPanes);
    boolean doubleClick=true;
    for(Pair p:roundPanes){
       LogUtil.log(p);
       String tag=BombUtil.clickOpen(p,$system,rowCount,columnCount);     
       Pane pane=new Pane(BombUtil.convertPair2String(p),p,tag,"" ); 
    
       Click click=new Click($subject,tag,BombUtil.convertPair2String(pane.getCoordinate()));
       insert(click);  
      
    } 
   
    
    
    LogUtil.log("double click pane over  ================="); 
end







rule 'click number'
ruleflow-group "click action"

when
    $click:Click($pid:pid,value != "0" && value != "*")    
    not Tag(pid==$pid)   
    $bombPic:BombPic()    
    $game:Game() 
     $room:Room()
      
then
    LogUtil.log("click number  start  =================");   
   
    
    
     Message tagMessage=new Message($pid,"mine",$click.getValue()); 
     insert(tagMessage);       
  
    Tag tag=new Tag($click.getUid(),$click.getValue(),$pid);
     insert(tag);
     
    retract($click); 
    LogUtil.log("click number over  ================="); 
end



rule 'click zero number'
ruleflow-group "click action"
when
    $click:Click($pid:pid,value == "0")  
    $bombPic:BombPic($system:system,$user:user)
    not Message(subject==$pid,predict=="mine")
    $game:Game()    
    $room:Room()
then
    LogUtil.log("click  zero number  start  ================= "+$click);   
     int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));#1*60*1000  
      LogUtil.log("=========");
	 int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));#1*60*1000  
	 Pair pair=BombUtil.convertString2Pair($pid);
    List<Pair> roundPanes=BombUtil.getRoundPanes(pair,rowCount,columnCount);
      LogUtil.log(pair+" list pair is   ================= "+roundPanes);  
    for(Pair p:roundPanes){
    
       String value=BombUtil.clickOpen(p,$system,rowCount,columnCount); 
       
       Click click=new Click($click.getUid(),value,BombUtil.convertPair2String(p));
       insert(click);
    }    
       
     Message tagMessage=new Message($pid,"mine",$click.getValue()); 
     insert(tagMessage); 
     
       Tag tag=new Tag($click.getUid(),$click.getValue(),$pid);
     insert(tag);
      retract($click);
    LogUtil.log("click zero number over  ================="); 
end










rule 'click mine'
ruleflow-group "game status"

when
    $click:Click(value=="*",$pid:pid,$uid:uid)
   
     
    $bombPic:BombPic($system:system,$user:user)    
    $game:Game($recordName:recordName)
  
    $count:Count()
    
then
    LogUtil.log("click mine start  ================="); 
  
     retract($click);
               
     Message tagMessage=new Message($pid,"mine","bomb"); 
     insert(tagMessage); 
     
      Message wrongMessage=new Message($uid,"wrong",$pid); 
     insert(wrongMessage); 
     
     Message gameOverMessage=new Message($recordName,"over","you lose"); 
     insert(gameOverMessage); 
      
     $game.setStatus("over");
     update($game);
    
   
    LogUtil.log("click mine over  ================="); 
end








rule 'taged click zero number'
ruleflow-group "clear click"
when
    $click:Click($pid:pid) 
    $game:Game()    
    $room:Room()
then
    LogUtil.log("taged click  zero number  start  ================= "+$click);   
     
      retract($click);
    LogUtil.log("taged click zero number over  ================="); 
end



rule 'complete'
ruleflow-group "game status"

when
    $bombPic:BombPic()
    $game:Game($recordName:recordName)    
    $count:Count($all:all,$bomb:bomb)    
    eval($bomb==$all)
    
    
then
    LogUtil.log("click mine start  ================="); 

     Message gameOverMessage=new Message($recordName,"over","win"); 
     insert(gameOverMessage); 
   
     
     $game.setStatus("over");
     update($game);
     
     
   
    LogUtil.log("click mine over  ================="); 
end







rule 'player logout  process count'
ruleflow-group "person count"
no-loop true
when
 $game:Game($playerCount:playerCount);
 $message:Message($subject:subject,predict=="logout")

then  
     LogUtil.log(" logout game live count start  ================="); 
      
     
    $game.setPlayerCount($playerCount-1);   
     update($game);
     LogUtil.log(" logout game live count over  ================="+$game); 
end


rule 'no player game over'
ruleflow-group "game status"
no-loop true
when
 $game:Game(playerCount<=0,status=="run",$recordName:recordName);
  $operater:Operater()  
  
 
then  
     LogUtil.log("no player game over start  ================="); 
      
     Message gameOverMessage=new Message($recordName,"over","lose"); 
     insert(gameOverMessage); 
           
     $game.setStatus("over");
     update($game);   
     LogUtil.log("no player game over over  ================="); 
end




rule 'game over process'
ruleflow-group "game status"

when
    
    $game:Game($recordName:recordName,status=="over")    
    $operater:Operater()  
    $count:Count()   
    $bombPic:BombPic($system:system,$user:user)
    $room:Room() 
    
       
    $allUserCount:ArrayList()
	      from accumulate(
	      $userCount:UserCount()	     
	      init(List ls=new ArrayList();),
	      action(ls.add($userCount);),
	      result(ls)
	      );
    
    
   
    
then
    LogUtil.log("game over processstart  ================="); 
    
     retract($game);
     retract($count);
     retract($bombPic);   
     
     for(Object o:$allUserCount){
        retract(o);
     }
    
     $room.setStatus("unrun"); 
     update($room);
     
     $operater.setGameOver(true);
     $operater.setRecordID(Long.valueOf($recordName));  
     
     
   
    LogUtil.log("game over process over  ================="); 
end



rule 'game over status '

ruleflow-group "game status"
when
     Game(status=="over") 
     $person:Player(status!="unready");
     
then 
     LogUtil.log("game over status start  ================="); 
    $person.setStatus("unready");   
    update($person);   
    
  
    LogUtil.log("game over status over  ================="); 
end








#========================game status group over =========================







#========================message group start =========================




rule 'time operater '
ruleflow-group "time of operater"

when
	#conditions	
    $message:Message($subject:subject,predict=="send time")
    $room:Room($rid:id,status=="run")
    $operater:Operater()
then      
    LogUtil.log("time operater  start  =============");   
    
    $message.setPredict("time");
    $message.setWhere($rid);

	$operater.getTimerMessages().add($message);		

    LogUtil.log("time operater over =============");
  
end







rule 'game player query'
ruleflow-group "query"
when
	#conditions
    $message:Message($subject:subject,predict=="query")
    $room:Room(status=="run")
    $allLogins:ArrayList()
	      from accumulate(
	      $person:Player()	     
	      init(List ls=new ArrayList();),
	      action(ls.add($person);),
	      result(ls)
	      );
	$game:Game($status:status);  
    $operater:Operater()
    $bombPic:BombPic()   
  
    $tags:ArrayList()
	      from accumulate(
	      $tag:Tag()	     
	      init(List ls=new ArrayList();),
	      action(ls.add($tag);),
	      result(ls)
	      );
  
  
    $allUserCount:ArrayList()
	      from accumulate(
	      $userCount:UserCount()	     
	      init(List ls=new ArrayList();),
	      action(ls.add($userCount);),
	      result(ls)
	      );
   
    
    
then      

	 LogUtil.log("get player query info =================");	 
      Map m=new HashMap();
      m.put("room",$room);
      m.put("person",$allLogins);     
      setRemainTime($status+"Time",$game,$room) ; 
      m.put("game",$game);     
     int  rowCount=Integer.valueOf(getRoomSetting($room,"行数","9"));	 
     int  columnCount=Integer.valueOf(getRoomSetting($room,"列数","9"));
     String bomb=BombUtil.initBomb(rowCount,columnCount);
     for(Object o:$tags){
        Tag tag=(Tag)o;
       Pair p=  BombUtil.convertString2Pair(tag.getPid());
        int index=BombUtil.convertIndex((Integer)p.fst, (Integer)p.snd, rowCount);
		bomb=BombUtil.replaceBomb(index, bomb, tag.getValue());
      } 
      $bombPic.setUser(bomb);
      m.put("bomb",$bombPic); 
       m.put("votes",$allUserCount);  
       
      $operater.setSnapshots(GsonUtil.toJson(m));     
      retract($message);   
	  LogUtil.log("get player query info over =================");
end












#========================message group over =========================


  