package drools.common

import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import org.apache.commons.lang.StringUtils;


declare Game
	status: String
	liverCount:int		
	waterCount:int
	wolfCount:int		
	burgCount:int
	dismissalCount:int
	currentBurg:int
	bombBurgCount:int
	unbombBurgCount:int
	lastTime:Long
	remainTime:Long
	startAt:Long
	recordName:String	
end
#index of action attempts,  attempts ++
#<String> when king dispatch , we get this value
#dismissal result,when player dismissal,we get this value 
declare ActionDetail
        attempts:int 
        members:List 
        dismissal:String  
        king:String    
end


#<attempts,ActionDetail>,when king is be dismissal,actionDetails get new Details.
declare Burg
        id:int
        actionDetails:Map
        result:String
        memberCount:int
        attemptCount:int
        bombWolfCount:int
             
        
end




declare King
       id:String
       index:int
       
end

declare KingDie
        id:String            
end

declare KingLiving
        id:String         
end




declare BurgDie
        id:int
        kid:String
end

declare BurgLiving
        id:int
        kid:String
end

#create bombAction when dismissal is agree
declare BombAction
    id: String
    burgID:int
    result:String
end

declare Dismissal
	id: String		
	result:String
	
end



declare Role
       id:String
       role:String      
end


declare Die
	id: String
	type: String
	role:String
end



declare StatusChange
     change:String
end


declare TimerMesasage
	phase: String
	time: Long
	schedule:Long
end

declare LivingPlayers
      players:List
end

