package drools.common

import drools.common.*
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.Collections;



import org.apache.commons.lang.StringUtils;




function void setRemainTime(String status,Game game,Room room) {

     if("day"==status){
       status="dayTime";
     };
     
     if("night"==status){
       status="nightTime";
     };
     
     if("lastword"==status){
       status="lastwordTime";
     };
     
    
     Long setting=Long.valueOf(getRoomSetting(room,status,"-1"));
      Long lastTime=game.getLastTime();
      Long time=lastTime+setting-System.currentTimeMillis();
      if(time < 0){
            LogUtil.log("=========== error ======= "+time);          
      }else{
          game.setRemainTime(time);
      }
     
       
}



function List<String>  getIDFromPlayer(List players) {

      List<String> pids=new ArrayList();
	    for(Object o:players){
	          Player p=(Player)o;			 
			  pids.add(p.getId());
		}
		return pids;
}


function Message createDelayNight(Room room) {

    String  timeSetting=getRoomSetting(room,"nightTime","30000");//1*60*1000 
    Message night=new Message("night","send time",timeSetting);
    String  time=getRoomSetting(room,"dayTime","15000");//1*60*1000
    night.setScheduledTime(Long.valueOf(time));
    
    return night;
  
}

 



function Message createDay(Room room) {
    String  dayTime=getRoomSetting(room,"dayTime","30000");//1*60*1000
    Message day=new Message("day","time",dayTime);
 
     return day;
   
  
}


    
    
   













