package drools.common

import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import org.apache.commons.lang.StringUtils;


declare Game
	status: String
	liverCount:int	
	waterCount:int
	killerCount:int
	policeCount:int
	lastTime:Long
	remainTime:Long
	startAt:Long
	recordName:String	
end

declare VoteConvert
	id: String		
	vote:String
	type:String
end


declare Vote
	id: String		
	vote:String
	type:String
end

declare VoteStatus
      id:String
      voters:List
      killerVoters:List
      policeVoters:List    
end

declare VoteCommonStatus
      id:String
      voters:List
end

declare Role
       id:String
       role:String
       status:String
end


declare Die
	id: String
	type: String
	role:String
end

declare KillConfirm
	id: String	
end
declare CheckConfirm
	id: String	
end

declare StatusChange
     change:String
end


declare TimerMesasage
	phase: String
	time: Long
	schedule:Long
end

