package drools.common

import drools.common.*
import com.gemantic.killer.common.model.Message
import com.gemantic.killer.common.model.Operater;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import  com.gemantic.common.util.json.GsonUtil;
import java.util.HashMap;
import java.util.Map;
import org.apache.commons.lang.math.RandomUtils;
import org.apache.commons.lang.StringUtils;
import com.gemantic.killer.util.*;





//===========game prepare will process clear info,role assing ,right assign

//========== 



rule 'clear prev game role '
ruleflow-group "game clear"
no-loop true
when
	//conditions    
    $message:Message($subject:subject,predict=="start")   
    $role:Role()    //clear source    
    
then      
	//actions
     LogUtil.log("clear prev game role start================= ");      
     retract ($role);
     LogUtil.log("clear prev game role over ================="); 
    
end
  
rule 'clear prev game vote '
ruleflow-group "game clear"
no-loop true
when
	//conditions    
    $message:Message($subject:subject,predict=="start")   
    $vote:Vote()    //clear source    
    
then      
	//actions
     LogUtil.log("clear prev game vote start================= ");      
     retract ($vote);
     LogUtil.log("clear prev game vote over ================="+$vote); 
    
end

rule 'clear prev game VoteStatus '
ruleflow-group "game clear"
no-loop true
when
	//conditions    
    $message:Message($subject:subject,predict=="start")   
    $voteStatus:VoteStatus()    //clear source    
    
then      
	//actions
     LogUtil.log("clear prev game VoteStatus start================= ");      
     retract ($voteStatus);
     LogUtil.log("clear prev game VoteStatus over ================="); 
    
end


//===================clear game over 


rule 'init'
ruleflow-group "game prepare"
no-loop true
when
	//conditions    
    $message:Message($subject:subject,predict=="start",$time:time)
    $room:Room(status=="unrun")  
    not Game()  
    
    //get all players
    $all_login_ids:HashSet()
	      from accumulate(
	      Player($id:id)	     
	      init(Set ls=new HashSet();),
	      action(ls.add($id);),
	      result(ls)
	      );
	      
    //get all readys
    $allReadys:ArrayList()
	      from accumulate(
	      $person:Player(status=="ready")	     
	      init(List ls=new ArrayList();),
	      action(ls.add($person);),
	      result(ls)
	      );
	      
	$unReadys:ArrayList()
      from accumulate(
	      $person:Player(status=="unready")	     
	      init(List ls=new ArrayList();),
	      action(ls.add($person);),
	      result(ls)
	      );
     //get operater
     $operater:Operater()
    
    //clear source    
    
then      
	//actions
   
     LogUtil.log("game init process start =================");
     //0 setGameName 
     String	rname=String.valueOf(RandomUtils.nextLong());
     //1.assign role	
	 int  killerCount=Integer.valueOf(getRoomSetting($room,"killerCount","1")); 
	 int  policeCount=Integer.valueOf(getRoomSetting($room,"policeCount","1")); 
	 int  waterCount= $allReadys.size()-killerCount-policeCount;
	 
	 Map role_count=new HashMap();
		role_count.put("killer", killerCount);
	    role_count.put("police", policeCount);
		role_count.put("water", waterCount);

	 //get uid id List
	 List ls=getIDFromPlayer($allReadys);
	 Map	ids_role=RoleUtil.assingRole(role_count,ls);
	 
	 //2. creae game
	Game game=new Game("ready",$allReadys.size(),waterCount,killerCount,policeCount,System.currentTimeMillis(),0L,$time,rname);
	
	 List readyIDS=new ArrayList();
	 //3.create Role/status/vote record message create log ,how to update all unready players status;
	 
		LogUtil.log("============================ role is "+ids_role);
		for(Object o: $allReadys){
			     Player p=(Player)o;			   
			    String uid=p.getId();
			    readyIDS.add(Long.valueOf(uid));
			    String role=(String)ids_role.get(uid);			      
				  modify(p){setStatus("living")};
				  
				  Role r=new Role(uid,role,"living");
				  insert(r);	  
				  
				  
				  LogUtil.log(role);
				  Message assignMessage=new Message(role,"assign",uid); 
				  insert(assignMessage);	  
				  
				   Message livingMessage=new Message(uid,"living",""); 
				  insert(livingMessage);
		            
		       JobLogger.logMessages(rname,Arrays.asList(new Message[]{new Message(uid,"ready",""),new Message(uid,"login","")}));			
	  	
			
		}

	
	
	
	//4 update room status ||repeat with game			
	modify($room){setStatus("run")};
	
	
	
 
     
	 
     StatusChange sc=new StatusChange("day");
     insert(sc);
	//6.update game phase	
   
    insert(game);

    
	
	
	
	LogUtil.log("game init process over  =================");
	
	//7. update operater 
	$operater.setGameStart(true);
	$operater.setPlayers(readyIDS);
        
   
end
//===========game prepare will process clear info,role assing ,right assign============over 

//========================phase clear start =========================



rule 'phase clear vote '
ruleflow-group "phase clear"
no-loop true
when
	//conditions    
    $vote:Vote()
    $room:Room(status=="run")
    (Game(status=="day") and Message($subject:subject,predict=="time",subject=="day"))   
    or 
    (Game(status=="night") and Message($subject:subject,predict=="time",subject=="night"))  
	 or 
    (Game(status=="lastword") and Message($subject:subject,predict=="time",subject=="lastword"))   
    
then      
	//actions
   //actions
     LogUtil.log("phase clear vote start================= "); 
     retract($vote);
     LogUtil.log("phase clear vote over =================");   
end




rule 'phase clear voteStatus '
ruleflow-group "phase clear"
no-loop true
when
	//conditions    
    $voteStatus:VoteStatus($voteMe:voteMe)
    eval($voteMe.size() > 0)
    $room:Room(status=="run")
    (Game(status=="day") and Message($subject:subject,predict=="time",subject=="day"))   
    or 
    (Game(status=="night") and Message($subject:subject,predict=="time",subject=="night"))  
	 or 
    (Game(status=="lastword") and Message($subject:subject,predict=="time",subject=="lastword"))   
    
then      
	//actions
   //actions
     LogUtil.log("phase clear vote start================= "); 
    
     modify($voteStatus){setVoteMe(new ArrayList()),setType("")};	
     LogUtil.log("phase clear vote over =================");   
end

rule 'phase clear right '
ruleflow-group "phase clear"
no-loop true
when
	//conditions    
    $right:Right()
    $room:Room(status=="run")
    (Game(status=="day") and Message($subject:subject,predict=="time",subject=="day"))   
    or 
    (Game(status=="night") and Message($subject:subject,predict=="time",subject=="night"))  
	 or 
    (Game(status=="lastword") and Message($subject:subject,predict=="time",subject=="lastword"))   
    
then      
	//actions
   //actions
     LogUtil.log("phase clear right start================= "); 
     retract($right);
     LogUtil.log("phase clear phase over =================");   
end


//===========phase clear============over 





//===========phase action============start 


rule 'first vote'
ruleflow-group "phase action"
no-loop true
when
    $message:Message($subject:subject,$object:object,predict=="vote")
    $voteStatus:VoteStatus(id==$object,$voteMe:voteMe)    
    Player(id==$subject,status=="living")
    Player(id==$object,status=="living")
    Game($status:status,$liverCount:liverCount)
    not Vote(id==$subject)
    Right(id==$subject,right contains "vote")
    Role(id==$subject,$role:Role)
    
then
    LogUtil.log("first vote start  ================="); 
     String voteType="wate";   
     if("day".equals($status)){
     
     }else{
     
       if("night".equals($status)){
         if("police".equals($role)){
            voteType="check";
         }else{
           if("killer".equals($role)){
             voteType="kill";
           }
            
         }
       }
     }
     Vote vote=new Vote($subject,$object,voteType);
     insert(vote);		
                   
    $voteMe.add($subject);
     modify($voteStatus){setVoteMe($voteMe)};
          LogUtil.log($liverCount+"change vote "+$voteStatus); 
    
     Message setVoteMessage=new Message($object,"set vote",String.valueOf($voteMe.size()));
     insert(setVoteMessage);      
      LogUtil.log("first vote over  ================="); 
end

rule 'change vote'
ruleflow-group "phase action"
no-loop true 
when
    $message:Message($subject:subject,$object:object,predict=="vote")
    $right:Right(id==$subject,right contains "vote")
    Vote(id==$subject)
    $oldVote:Vote(id==$subject,$old:vote)
    $newVoteStatus:VoteStatus(id==$object,$newVoteMe:voteMe)
    $oldVoteStatus:VoteStatus(id==$old,$oldVoteMe:voteMe)
    Player(id==$subject,status=="living")
    Player(id==$object,status=="living")
    $game:Game($status:status)
    Role(id==$subject,$role:Role)
    eval($old!=$object)
then
    LogUtil.log("change vote start  ================="); 
    retract($oldVote);
    
     
     String voteType="wate";   
     if("day".equals($status)){
     
     }else{
     
       if("night".equals($status)){
         if("police".equals($role)){
            voteType="check";
         }else{
           if("killer".equals($role)){
             voteType="kill";
           }
            
         }
       }
     }
     Vote vote=new Vote($subject,$object,voteType);
     insert(vote);
     
     $oldVoteMe.remove($subject);
     modify($oldVoteStatus){setVoteMe( $oldVoteMe)};	
                   
     $newVoteMe.add($subject);
     modify($newVoteStatus){setVoteMe($newVoteMe)};
         LogUtil.log("change vote "+$newVoteStatus); 
     
    
     Message addSetVoteMessage=new Message($object,"set vote",String.valueOf($newVoteMe.size()));
     insert(addSetVoteMessage);     
      Message subractSetVoteMessage=new Message($old,"set vote",String.valueOf($oldVoteMe.size()));
     insert(subractSetVoteMessage);
      LogUtil.log("change vote over  ================="); 
end




//===========phase action============over



//==person status==start


rule 'person die by vote'
ruleflow-group "person status"
no-loop true
when
 
  
  $game:Game(status=="day",$liverCount:liverCount);
  $person:Player($id:id,status=="living");
  $voteStatus:VoteStatus(id==$id)     
  eval(($voteStatus.getVoteMe().size() * 2) > $liverCount )   
  Role(id==$id,$role:role)
then
   LogUtil.log("person die  start==============");
   Die die=new Die($id,"vote",$role);   
   insert(die);
   LogUtil.log("person die  start==============");   

 
end


//==person status ===over 




//==die process==


rule 'die process'
ruleflow-group "die process"
no-loop true
when
 
  $die:Die($id:id,$type:type,$role:role)
  $game:Game($liverCount:liverCount,$waterCount:waterCount,$killerCount:killerCount,$policeCount:policeCount,$status:status);
  $person:Player(status=="living");   
 then
   LogUtil.log(" die  start=============");
   
   //if water die
    if("water".equals($role)){
        modify($game){setLiverCount($liverCount-1),setWaterCount($waterCount-1)};
    
    }else{
     //if police die
       if("police".equals($role)){
       
         modify($game){setLiverCount($liverCount-1),setPoliceCount($policeCount-1)};
    
       }else{
          //if killer die
          modify($game){setLiverCount($liverCount-1),setKillerCount($killerCount-1)};
          
       
       }    
    } 
    if("vote".equals($type)){
    
     //if die of vote 
     Message decryption=new Message($id,"decryption",$role);  
     insert(decryption);
    }
    	
    
    retract($die);
    
    

 
end


//==person status ===over 

//==game status===start 


rule 'game over of  killer win'
ruleflow-group "game status"
when
   
     $game:Game($killerCount:killerCount,$waterCount:waterCount,$policeCount:policeCount,$recordName:recordName);
    ( eval($killerCount >= $waterCount+$policeCount))     
     or
    ( eval($policeCount==0))
     
     $room:Room(status=="run")
  
	      
      
then 
     LogUtil.log("game over kill win start  ================="); 

    
    Message gameOver=new Message($recordName,"over","killer win");   
    insert(gameOver);
  
   
  
    
      
      
      LogUtil.log("game over kill win over  ================="); 
end

rule 'game over of water win'

ruleflow-group "game status"
when
     //$operater:Operater()  
     $game:Game($killerCount:killerCount,$waterCount:waterCount,$recordName:recordName);
     eval($killerCount == 0 )  
     $room:Room(status=="run")
      
then 
     LogUtil.log("game over water start  ================="); 
  
    Message gameOver=new Message($recordName,"over","water win");   
    insert(gameOver);    
  
      LogUtil.log("game over water over  ================="); 
end

//===========game status ============over 

rule 'game over process '

ruleflow-group "game status"
no-loop true
when
     //$operater:Operater()  
     Message(predict=="over",$object:object)
     $game:Game();
     $room:Room(status=="run")     
     $all_login_ids:HashSet()
	      from accumulate(
	      Player($id:id)	     
	      init(Set ls=new HashSet();),
	      action(ls.add($id);),
	      result(ls)
	 );
	 $all_role:HashMap()
	      from accumulate(
	      $role:Role($id:id)	     
	      init(Map map=new HashMap();),
	      action(map.put($id,$role);),
	      result(map)
	      );
	      
	 
	 	 $all_right:HashMap()
	      from accumulate(
	      $right:Right($id:id)	     
	      init(Map map=new HashMap();),
	      action(map.put($id,$right);),
	      result(map)
	      );
	 $operater:Operater()  
      
then 
     LogUtil.log("game over process  start  ================="); 
     String rightContent="say,ready";
     for(Object o:$all_login_ids){
            String uid=(String)o;
            Role role =(Role)$all_role.get(uid);
            if(role==null){
            
            
            }else{
            
             if("water".equals(role)){
             
             
             }else{
               //decryption or money or other 
                
              Message decryption=new Message(uid,"decryption",role.getRole());  
               insert(decryption);
                
             }
            
            retract(role)
            
            }
            
            
            
            Right right =(Right)$all_right.get(uid);
            
            if(right==null){
               right= new Right(uid,convertString2Set(rightContent),false);
               insert(right);	
            }else{
               Set rights=convertString2Set(rightContent);
            
               modify(right){setRight(rights)};
            
            
            }            
            
            
	        Message rightMessage=new Message(uid,"right",rightContent); 
            insert(rightMessage);		
	  
            
        
	
	
     
     
     }
      
   
      modify($room){setStatus("unrun")};
      modify($operater){setGameOver(true)};
      retract($game);   
    
      LogUtil.log("game over process  over  ================="); 
end




//============game over = ============start 




//============game over =============over 

//===========switch ============start 

rule 'phase switch '
ruleflow-group "phase switch"
no-loop true
when
	//conditions    
	$statusChange:StatusChange($change:change)
    $room:Room(status=="run")
    $game:Game() 
    $operater:Operater()
    
then      
	//actions 
     LogUtil.log("phase switch start================= "); 
     List tms=$operater.getTimerMessages();
    
    if("day".equals($change)){
    
      //1.set game phase,set last time,
          
    modify($game){setStatus("day"),setLastTime(System.currentTimeMillis())};
    
    
    
     //2.send delay timer of night    
	Message nightDelay=createDelayNight($room);	
	tms.add(nightDelay);      
  


    
    //3.insert day come 
    insert(createDay($room)); 
    
    }else{
    
       if("lastwords".equals($change)){
       
       
           //1.set game phase,set last time,
          
          modify($game){setStatus("lastword"),setLastTime(System.currentTimeMillis())};
          //2.send timer of night    
	     Message dayDelay=createDelayDayOfLastword($room);
         tms.add(dayDelay); 
    
           //3.insert day come 
          insert(createLastword($room)); 
       
       }else{
          //night 
       
          modify($game){setStatus("night"),setLastTime(System.currentTimeMillis())};
           //2.send timer of night    
	      Message dayDelay=createDelayDayOfNight($room);
          tms.add(dayDelay);  
    
          //3.insert day come 
          insert(createNight($room)); 
       
       
       }
    
    }
    
      modify($operater){setTimerMessages(tms)};
   
          
     LogUtil.log("phase switch  over =================");   
end



//===========switch ============over 

//===========phase prepare ============start  

rule 'day phase prepare right'
ruleflow-group "phase prepare"
no-loop true
when
	//conditions
	$player:Player(status=="living",$uid:id)
	Message($subject:subject,predict=="time",subject=="day")
	 
    Room(status=="run")
    Game(status=="day")
    not Right(id==$uid)
    not VoteStatus(id==$uid)    
then      
	//actions 
     LogUtil.log("day phase prepare  start================= "); 
     // set right ,use query
     Right right= new Right($uid,convertString2Set("say,vote"),false);		
	 insert(right);	
	
	 // send right message
	 Message rightMessage=new Message($uid,"right","say,vote"); 
     insert(rightMessage);
     
    VoteStatus voteStatus=new VoteStatus($uid,new ArrayList(),"water");
     insert(voteStatus);	
		            
          
     LogUtil.log("day phase prepare  over =================");   
end

rule 'night phase prepare right'
ruleflow-group "phase prepare"
no-loop true
when
	//conditions
	$player:Player(status=="living",$uid:id)
	Message($subject:subject,predict=="time",subject=="night")
	 
    Room(status=="run")
    Game(status=="day")
    not Right(id==$uid)
    not VoteStatus(id==$uid)    
    Role(id==$uid,$role:role)
then      
	//actions 
     LogUtil.log("night phase prepare  start================= ");
     String rightContent=""; 
     String voteType="";
     // set right ,use query
     if("killer".equals($role)){
         rightContent="say,kill";
              
         Right right= new Right($uid,convertString2Set(rightContent),false);		
	      insert(right);		
	      // send right message
	     Message rightMessage=new Message($uid,"right",rightContent); 
          insert(rightMessage);
              
           VoteStatus voteStatus=new VoteStatus($uid,new ArrayList(),"kill");
           insert(voteStatus);
           
     }else{
       if("police".equals($role)){       
          rightContent="say,check";
           
         Right right= new Right($uid,convertString2Set(rightContent),false);		
	      insert(right);	
	
	    // send right message
	     Message rightMessage=new Message($uid,"right",rightContent); 
         insert(rightMessage);
	
               
         VoteStatus voteStatus=new VoteStatus($uid,new ArrayList(),"check");
         insert(voteStatus);
       }else{
        
         
         
       }
     
    }
		            
          
     LogUtil.log("night phase prepare  over =================");   
end


rule 'lastword phase prepare right'
ruleflow-group "phase prepare"
no-loop true
when
	//conditions
	$player:Player(status=="lastword",$uid:id)
	Message($subject:subject,predict=="time",subject=="lastword")
	 
    Room(status=="run")
    Game(status=="lastword")
    not Right(id==$uid)
   
then      
	//actions 
     LogUtil.log("lastword phase prepare  start================= "); 
     // set right ,use query
     Right right= new Right($uid,convertString2Set("lastword"),false);		
	 insert(right);	
	
	 // send right message
	 Message rightMessage=new Message($uid,"right","lastword"); 
     insert(rightMessage);

		            
          
     LogUtil.log("lastword phase prepare  over =================");   
end


//===========phase prepare============over 

//===========message accept============start 



rule 'single accept of assign'
ruleflow-group "message accept"
salience 100
no-loop true 
when
     $message:Message($subject:subject,predict=="assign",$object:object,$accepts:accepts)   
	 
	 
then
     LogUtil.log(" single accept of assign start  ============="+$message);        
     $accepts.add($object); 
     modify($message){setAccepts($accepts)};    
    LogUtil.log("single accept of assign over =============");
    
end
  
rule 'single accept of right'
ruleflow-group "message accept"
salience 100
no-loop true 
when
     $message:Message($subject:subject,predict=="right",$object:object,$accepts:accepts)   
	 
	 
then
     LogUtil.log(" single accept of right start  ============="+$message); 
     $accepts.add($subject);        
     modify($message){setAccepts($accepts)};    
    LogUtil.log(" single accept of right over =============");
    
end


rule 'group accept of say'
ruleflow-group "message accept"
salience 50
no-loop true 
when
     $message:Message($subject:subject,predict=="say"||predict=="vote",object=="-500",$accepts:accepts)   
	 Role(id==$subject,$role:role)
	 $otherRole:Role($oid:id,role==$role)
	 Game(status=="night")
	 
then
     LogUtil.log(" group say start  ============="+$message);   
     $accepts.add($oid);
     modify($message){setAccepts($accepts)};    
    LogUtil.log("group say over =============");
    
end



rule 'all accept of all'
ruleflow-group "message accept"
salience 0
no-loop true 
when
    $message:Message($accepts:accepts)   
	eval($message.getAccepts().size()==0)
   $all_login_ids:HashSet()
	      from accumulate(
	      Player($id:id)	     
	      init(Set ls=new HashSet();),
	      action(ls.add($id);),
	      result(ls)
	      );
	 
then
     LogUtil.log(" all accept start  ============="+$message);         
     modify($message){setAccepts(new ArrayList($all_login_ids))};    
    LogUtil.log("all accept over =============");
    
end


//===========message accept============over 
