package drools.common

import drools.common.*
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.Collections;
import com.gemantic.common.drools.util.LogUtil;


import org.apache.commons.lang.StringUtils;
import com.gemantic.killer.util.*;

function String getRoomSetting(Room room,String name,String defaultValue) {

   Map setting=room.getSetting();
   String value=(String)setting.get(name);
    if(StringUtils.isBlank(value)){
        LogUtil.log(name+" setting is not find value "+setting);
       return defaultValue;

    }else{
    
    return value;
    }

}




function Set convertString2Set(String value) {

   Set s=new HashSet();
   String[] aa=value.split(",");
   for(String str:aa){
      s.add(str);
   }
   
    return s;
}






 














